# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

# This pipelines builds Linux image

trigger:
- master

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: 'acragentimagepurpose'
  imageRepository: 'azuredevopsagents'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  
stages:
- stage: Build
  displayName: Build and push stage
  jobs:  
  - job: Build_Linux_Ubuntu
    displayName: Build Linux Images(s)
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)/ubuntu
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(Build.BuildId)
          latest